name: Glob match
description: Search for files matching glob patterns.
author: tj-actions
inputs:
  files:
    description: 'File patterns'
    required: false
  files-separator:
    description: 'Separator used to split the `files` input'
    default: "\n"
    required: false
  excluded-files:
    description: 'Excluded file patterns (optionally include `!` before the file pattern or it would be prepended)'
    required: false
    default: ""
  excluded-files-separator:
    description: 'Separator used to split the `excluded-files` input'
    default: "\n"
    required: false
  files-from-source-file:
    description: 'Source file to populate the `files` input'
    required: false
    default: ""
  files-from-source-file-separator:
    description: 'Separator used to split the `files-from-source-file` input'
    default: "\n"
    required: false
  excluded-files-from-source-file:
    description: 'Source file to populate the `excluded-files` input'
    required: false
    default: ""
  excluded-files-from-source-file-separator:
    description: 'Separator used to split the `excluded-files-from-source-file` input'
    default: "\n"
    required: false
  follow-symbolic-links:
    description: 'Indicates whether to follow symbolic links'
    default: "true"
    required: true
  separator:
    description: 'Separator used for the paths output.'
    required: true
    default: " "
  escape-paths:
    description: 'Escape special characters of filenames used in the `paths` output'
    required: false
    default: false
  strip-top-level-dir:
    description: 'Strip the `$GITHUB_WORKSPACE` from the `paths` output'
    required: false
    default: "true"
  include-deleted-files:
    description: 'Include all matching deleted files'
    required: false
    default: "false"
  sha:
    description: 'Specify a current commit SHA used for comparing changes, when `include-deleted-files` is set to `true`'
    required: true
    default: ${{ github.sha }}
  base-sha:
    description: 'Specify a base commit SHA used for comparing changes, when `include-deleted-files` is set to `true`'
    required: false
  working-directory:
    description: 'Specify a relative path under $GITHUB_WORKSPACE to locate the repository'
    required: true
    default: '.'

outputs:
  paths:
    description: "List of filtered paths using the specified patterns and separator"
  paths-output-file:
    description: "List of filtered paths using the specified patterns and separator stored in a tempfile"

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'

branding:
  icon: filter
  color: white
