name: Publish package to GitHub Packages
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Run semver-diff
        id: semver-diff
        uses: tj-actions/semver-diff@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: yarn publish -${{ steps.semver-diff.outputs.release_type }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
