name: Renovate config validation

on:
  push:
    branches: [main]
    paths:
      - renovate.json
      - .github/workflows/renovate.yml
  pull_request:
    branches: [main]
    paths:
      - renovate.json
      - .github/workflows/renovate.yml

jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: tj-actions/renovate-config-validator@v2
