name: Renovate config validation

on:
  push:
    branches: [main]
    paths:
      - renovate.json
      - .github/workflows/renovate.yml
  pull_request:
    branches: [main]
    paths:
      - renovate.json
      - .github/workflows/renovate.yml

jobs:
  renovate-config-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4
      - uses: tj-actions/renovate-config-validator@v2
